server.port = 9005


access-point.rules-api-url=${rules_api_url:http://localhost:9004}
access-point.sims-api-url=${sims_api_url:http://localhost:9010}
access-point.layouts-api-url=${layouts_api_url:http://localhost:9003}